all:
	# Make in subfolder
	make -C sample1 -f Makefile
	make -C sample2 -f Makefile
	make -C memory -f Makefile
	make -C phocrexample -f Makefile
	make -C msm_performance_test -f Makefile
	make -C msm_sample/190909_D476_PHOcrSample -f Makefile
	make -C cancel_phocr -f Makefile
