# TOSHIBA - TSDV
# Team:             OCRPoc
# Author:           Phung Dinh Tai
# Email:            tai.phungdinh@toshiba-tsdv.com
# Date create:      20/06/2018
# Last update:
# Description:
import argparse
import sys_path
sys_path.insert_sys_path()
from report.lib_errors_report.bb_error_types_reporter import BbErrorTypesReporter


def parse_arguments():
    # Parsing arguments
    parser = argparse.ArgumentParser(description="Export accuracy report of PHOcr product.")
    parser.add_argument("-r", "--test-file", required=True,
                        help="Json file that is generated from executing run_all.py script")
    parser.add_argument("-c", "--compare-file", required=True,
                        help="Compare json file which is generated by compare_all.py")
    parser.add_argument("-t", "--test-folder", required=True,
                        help="folder of OCR result generated from using run_all.py script")
    parser.add_argument('-o', '--output-file',
                        help='Name of report and should be tsv format')
    return parser


def main():
    # Parse arguments
    parser = parse_arguments()
    args = parser.parse_args()

    # Initial reporter
    reporter = BbErrorTypesReporter(test_file=args.test_file,
                                    compare_file=args.compare_file,
                                    test_folder=args.test_folder)
    # Make report
    reporter.do_work()


if __name__ == "__main__":
    main()