# TOSHIBA - TSDV
# Team:             PHOcr
# Author:           Phung Dinh Tai
# Email:            tai.phungdinh@toshiba-tsdv.com
# Date create:      18/09/2019
# Description:      By refer to log folder which is generated by automation test system when
#                   calling to nodes_manager.py, this class help us generate all reports for
#                   system performance for build/test processes on all run times.
import os
from baseapi.log_manager import Logger
from baseapi.file_access import remove_paths, make_dir
from configs.test_result import FinalTestResult
from report.lib_system_performance.execution_time_data_parser import ExecutionTimeDataParser
from report.lib_system_performance.system_performance_reporter import SystemPerformanceReporter


class SystemPerformanceReportsGenerator(object):
    # Name of log folder for master of test system
    LOG_MASTER_FOLDER = "log_master"
    # Name of master
    MASTER = "master"
    # Prefix for log folder from nodes
    LOG_FOLDER_PREFIX = "log_"
    # Specific for report execution time of build processes to distinguish with report for test
    # processes
    BUILD_REPORT_SPECIFIC = "build"
    # Specific for execution time report of test processes
    TEST_REPORT_SPECIFIC = "test"

    def __init__(self, log_folder=None, output_folder=None):
        """
        Constructor for reports generator of system performance. To generate reports, user need
        to define the location of log folder of test system. Currently, this folder has structure
        like following:
        <log_folder>
            |__log_build
            |  |__run_1
            |     |__log_master
            |     |__log_<node1>
            |     |__...
            |
            |__log_test
               |__run_1
               |  |__log_master
               |  |__log_<node>
               |  |__...
               |__run_2
               |  |...
               |__...


        Parameters
        ----------
        log_folder: str
            Path to log folder which is generated from calling to nodes_manager.py
        output_folder: str
            Path to output folder which will be storage reports

        """
        self.log_folder = log_folder
        self.output_folder = output_folder

    @property
    def log_folder(self):
        """
        Getter for path to log folder of automation test system where store all logging
        information of test system.

        Returns
        -------
        str
            Path to log folder which is generated from calling to nodes_manager.py

        """
        return self._log_folder

    @log_folder.setter
    def log_folder(self, path):
        """
        Setter for path to log folder of automation test system from calling to nodes_manager.py

        Parameters
        ----------
        path: str
            Path to log folder of automation test system which is generated after calling to
            nodes_manager.py

        Returns
        -------
        None

        """
        self._log_folder = path

    @property
    def output_folder(self):
        """
        Getter for output folder of generator. This directory will storage all reports which are
        generated.

        Returns
        -------
        str
            Path to output folder of generator which storage all the reports

        """
        return self._output_folder

    @output_folder.setter
    def output_folder(self, path):
        """
        Setter for output folder of generator which will be used to storage all generated reports

        Parameters
        ----------
        path: str
            Path to destination directory which will be used to storage generated reports

        Returns
        -------
        None

        """
        self._output_folder = path

    def _generate_performance_reports_on_job(self, job_log_dir, job_specific):
        """
        Generate report for a job. Currently, we have 2 jobs: BUILD and TEST.

        Parameters
        ----------
        job_log_dir: str
            Path to log folder of the job. We can see in structure of log folder in constructor,
            this path is <log_folder>/log_build or <log_folder>/log_test
        job_specific: str
            Some string to distinguish reports from different jobs because they can be placed
            into the same location. We can just use name of the job in this case.

        Returns
        -------
        None

        """
        for run_time_folder in os.listdir(job_log_dir):
            run_time_log_dir = os.path.join(job_log_dir, run_time_folder)
            if os.path.isdir(run_time_log_dir):
                # Prepare path to output file report. Specify report for a run time of build
                # processes
                report_suffix = "_{job_specific}_{run_specific}".format(
                    job_specific=job_specific, run_specific=run_time_folder)
                report_name = SystemPerformanceReporter.TEMPLATE_NAME_OUTPUT_FILE.format(
                    suffix=report_suffix)
                # Push report to output folder
                report_file_path = os.path.join(self.output_folder, report_name)
                # Initial reporter
                reporter = SystemPerformanceReporter(output_file=report_file_path)
                # Execution time data from master of build job
                performance_data_file_master = \
                    Logger.DEFAULT_PERFORMANCE_DATA_JSON_FILE.format(self.MASTER)
                time_data_file = os.path.join(run_time_log_dir, self.LOG_MASTER_FOLDER,
                                              performance_data_file_master)
                # Create data parser object for execution time data from master
                data_parser = ExecutionTimeDataParser(input_file=time_data_file)
                data_parser.name = self.MASTER
                if job_specific == self.BUILD_REPORT_SPECIFIC:
                    reporter.master_build_data_parser = data_parser
                else:
                    reporter.master_test_data_parser = data_parser
                # Execution time data from nodes of build job
                # Get list of nodes name
                nodes = list()
                for node_log in os.listdir(run_time_log_dir):
                    node_log_path = os.path.join(run_time_log_dir, node_log)
                    if node_log.startswith(self.LOG_FOLDER_PREFIX) and os.path.isdir(node_log_path):
                        node_name = node_log.replace(self.LOG_FOLDER_PREFIX, "")
                        if node_name != self.MASTER:
                            nodes.append(node_name)
                # Collect system performance data and pass to reporter
                node_data_parsers = list()
                for node_name in nodes:
                    node_log_folder = self.LOG_FOLDER_PREFIX + node_name
                    node_log_path = os.path.join(run_time_log_dir, node_log_folder)
                    performance_data_file_node = \
                        Logger.DEFAULT_PERFORMANCE_DATA_JSON_FILE.format(node_name)
                    time_data_file = os.path.join(node_log_path, performance_data_file_node)
                    # Create data parser object for execution data from node
                    data_parser = ExecutionTimeDataParser(input_file=time_data_file)
                    data_parser.name = node_name
                    # Add data parser for node to the list
                    node_data_parsers.append(data_parser)
                # Setup data parsers for nodes in reporter
                if job_specific == self.BUILD_REPORT_SPECIFIC:
                    reporter.node_build_data_parsers = node_data_parsers
                else:
                    reporter.node_test_data_parsers = node_data_parsers

                # Generate report for build processes on the run time
                reporter.do_work()

    def generate_build_performance_reports(self):
        """
        Generate reports for performance of automation test system on build processes. Each run
        time of build will be reported in an excel report.

        Returns
        -------
        None

        """
        # Prepare output folder to storage generated reports
        if os.path.exists(self.output_folder):
            remove_paths(paths=self.output_folder)
        make_dir(self.output_folder)
        # Generate automation test system performance reports for BUILD processes
        build_log_folder = os.path.join(self.log_folder, FinalTestResult.Log.BUILD)
        if os.path.isdir(build_log_folder):
            self._generate_performance_reports_on_job(job_log_dir=build_log_folder,
                                                      job_specific=self.BUILD_REPORT_SPECIFIC)

    def generate_test_performance_reports(self):
        """
        Generate reports for performance of automation test system on test processes. Each run
        time of test will be reported in an excel report.

        Returns
        -------
        None

        """
        # Prepare output folder to storage generated reports
        if os.path.exists(self.output_folder):
            remove_paths(paths=self.output_folder)
        make_dir(self.output_folder)
        # Generate automation test system performance reports for TEST processes
        test_log_folder = os.path.join(self.log_folder, FinalTestResult.Log.TEST)
        if os.path.isdir(test_log_folder):
            self._generate_performance_reports_on_job(job_log_dir=test_log_folder,
                                                      job_specific=self.TEST_REPORT_SPECIFIC)

    def generate_reports(self):
        """
        Generate all reports for performance of automation test system of both build and test
        processes.

        Returns
        -------
        None

        """
        # Prepare output folder to storage generated reports
        if os.path.exists(self.output_folder):
            remove_paths(paths=self.output_folder)
        make_dir(self.output_folder)
        # Generate performance system reports for BUILD processes
        self.generate_build_performance_reports()
        # Generate performance system reports for TEST processes
        self.generate_test_performance_reports()
