# TOSHIBA - TSDV
# Team:             OCRPoc
# Author:           Phung Dinh Tai
# Email:            tai.phungdinh@toshiba-tsdv.com
# Date create:      16/05/2017
# Last update:      16/05/2107
# Description:      Parse data from text layout file which is generated by PHOcr

from data_object import Element

class Header:
    WORD = "***WORDS"
    CHARACTER = "***CHARACTERS"

class HtmlParser:
    # Initial
    def __init__(self):
        pass

    # Parse string to key and value 'left: 912px'
    # @return: dict with int value
    def extract_coord(self, str_info):
        result = self.extract_info(str_info)
        pix_str = result["value"]
        result["value"] = int(pix_str[:-2])
        return result

    # Parse key and value 'value : info'
    # @return: dict with key and value both are string
    def extract_info(self, str_info):
        str_split = str_info.split(":")
        result = {}
        result["key"] = str_split[0].strip()

        try:
            result["value"] = str_split[1].strip()
        except:
            result["value"] = ""

        return result

    # Parse line number 'Line: 320'
    # @return: int
    def extract_line_number(self, str_info):
        result = self.extract_info(str_info)
        return int(result["value"])

    # '"M"', 'Insert "e6"', '"i" Replace by: "l"', 'Delete "o"'
    def extract_ground_truth(self, str):
        str_split = str.split("\"")
        index = len(str_split) - 2
        return str_split[index]

    # Parse bounding box information 'left: 912px; top: 1801px; width: 53px; height: 32px;
    #  line-height: 32px;font-size: 32px;'
    # @return: dict
    def extract_bb(self, str_info):
        result = {}
        # Information which will be extracted
        key_list = ["left", "top", "width", "height"]

        for s in str_info.split(';'):
            info = self.extract_info(s)

            if (info["key"] in key_list):
                result[info["key"]] = info["value"]

        return result

class TextLayoutParser:
    # Initial
    def __init__(self, bb_file):
        self.file = bb_file
        self.word_list = []
        self.word_done = False
        self.char_list = []
        self.char_done = False

    # Parse key and value 'value : info'
    # @return: dict with key and value both are string
    def extract_info(self, str_info):
        str_split = str_info.split(":")
        result = {}
        result["key"] = str_split[0].strip()

        try:
            result["value"] = str_split[1].strip()
        except:
            result["value"] = ""

        return result

    # Parse bounding box information 'Bones: 603, 96, 114, 27'
    # @return: dict
    def extract_bb(self, str_info):
        tmp_info = self.extract_info(str_info)
        bb_str = tmp_info["value"].split(",")
        return Element(tmp_info["key"], int(bb_str[0]), int(bb_str[1]), int(bb_str[2]), int(bb_str[3]))

    # Extract data from layout text file to attributes
    def ParseWordData(self):

        with open(self.file, 'r') as data_file:
            start = False

            for line in data_file:

                if start:

                    try:
                        word = self.extract_bb(line)
                        self.word_list.append(word)
                    except:
                        break

                # Start to extract word data
                if Header.WORD == line.strip():
                    start = True

        self.word_done = True

    # Extract data from layout text file to attributes
    def ParseCharacterData(self):

        with open(self.file, 'r') as data_file:
            start = False

            for line in data_file:

                if start:

                    try:
                        char = self.extract_bb(line)
                        self.char_list.append(char)
                    except:
                        break

                # Start to extract data
                if Header.CHARACTER == line.strip():
                    start = True

        self.char_done = True

    # Extract both of character and word data
    def ParseData(self):
        self.ParseWordData()
        self.ParseCharacterData()

    # Get word list
    def GetWordList(self):

        if not self.word_done:
            self.ParseWordData()

        return self.word_list

    # Get character list
    def GetCharacterList(self):

        if not self.char_done:
            self.ParseCharacterData()

        return self.char_list
