# Generated by Django 2.0.3 on 2018-03-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MekongLogging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_tag', models.CharField(max_length=255)),
                ('log_type', models.CharField(max_length=255)),
                ('at_time', models.DateTimeField(verbose_name='Logging time')),
                ('client_name', models.CharField(max_length=255)),
                ('client_address', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=4000)),
            ],
        ),
    ]
