# Generated by Django 2.0.3 on 2018-03-28 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mekong_log', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MekongLogging',
            new_name='MekongLog',
        ),
    ]
