# Generated by Django 2.0.3 on 2018-03-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mekong_log', '0002_auto_20180328_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mekonglog',
            name='at_time',
            field=models.DateTimeField(blank=True, verbose_name='Logging time'),
        ),
        migrations.AlterField(
            model_name='mekonglog',
            name='log_tag',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mekonglog',
            name='log_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mekonglog',
            name='message',
            field=models.CharField(blank=True, max_length=4000),
        ),
    ]
