# Generated by Django 2.0.3 on 2018-03-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mekong_log', '0003_auto_20180328_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mekonglog',
            name='client_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
