# Generated by Django 2.0.3 on 2018-03-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mekong_log', '0004_auto_20180328_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mekonglog',
            name='client_name',
            field=models.CharField(max_length=255),
        ),
    ]
