/*****************************************************************************
 * Copyright 2017 TOSHIBA TEC Corporation
 * @file    UnitTestUtility.h
 * @brief
 * @author  Trong Nguyen Van<trong.nguyenvan@toshiba-tsdv.com>
 * @date    May 20, 2019
 *****************************************************************************/
#ifndef PHOCRTESTS_UNITTESTUTILITY_H_
#define PHOCRTESTS_UNITTESTUTILITY_H_

#include <string>

/**
 * This class is created with the idea is make our unit testing more easier by
 * proving some utility function to check status of result after PHOcr process.
 */
class UnitTestUtility {
 public:
  UnitTestUtility();
  virtual ~UnitTestUtility();

  /**
   * Get the current working path
   * @return
   */
  static std::string GetCurrentPath();

  static std::string GetCurrentPathToFileName(std::string file_name);

  /**
   * Check if a file exist or not
   * @param file_path
   * @return
   */
  static bool IsExistingFile(std::string file_path);

  /**
   * Delete a file by using the path to its location
   * @param file_path
   */
  static void DeleteFile(std::string file_path);

  /**
   * Delete all possible output file that is generated by PHOcr, including any
   * file with extension: .txt, .xml, .jpeg, .docx, .pptx, .xlsx, .pdf, .json
   */
  static void DeletePossiblePHOcrOutputFile();

  /**
   * Get the file name from the absolute file path
   * @param file_path
   * @return
   */
  static std::wstring GetFilenameFromFilepath(std::wstring file_path);

  /**
   * Read content of a file to string structure
   * @param file_path
   * @return
   */
  static std::string ReadContent(std::string file_path);

  /**
   * Create new directory by the path. If directory already exist, I will
   * delete
   * @param path
   */
  static bool CreateNewDirectory(const std::string& path);

  /**
   * Delete a directory recursively
   * @param path
   */
  static void DeleteDirectoryRecursive(const std::string& path);

  /**
   * Get the number of character (byte) of file_path, return -1 if file isn't
   * exist on disk
   * @param file_path
   * @return
   */
  static int GetFileSize(const std::string& file_path);
};

#endif  // PHOCRTESTS_UNITTESTUTILITY_H_ //
